# Generated by Django 2.2.19 on 2021-02-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('studant_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('year_of_graduat', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
