# Generated by Django 2.2.19 on 2021-03-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('recom_num', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('teach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
